In [1]:
pip install numpy


Note: you may need to restart the kernel to use updated packages.
     ---------------------------------------- 0.0/61.0 kB ? eta -:--:--
     ------ --------------------------------- 10.2/61.0 kB ? eta -:--:--
     ------ --------------------------------- 10.2/61.0 kB ? eta -:--:--
     ------------------------- ------------ 41.0/61.0 kB 326.8 kB/s eta 0:00:01
     -------------------------------------- 61.0/61.0 kB 323.6 kB/s eta 0:00:00
   ---------------------------------------- 0.0/15.8 MB ? eta -:--:--
   ---------------------------------------- 0.0/15.8 MB ? eta -:--:--
   ---------------------------------------- 0.0/15.8 MB 435.7 kB/s eta 0:00:37
   ---------------------------------------- 0.0/15.8 MB 281.8 kB/s eta 0:00:56
   ---------------------------------------- 0.1/15.8 MB 297.7 kB/s eta 0:00:53
   ---------------------------------------- 0.1/15.8 MB 353.1 kB/s eta 0:00:45
   ---------------------------------------- 0.1/15.8 MB 308.0 kB/s eta 0:00:52
   ------------------

ERROR: Could not install packages due to an OSError: [WinError 2] The system cannot find the file specified: 'C:\\Python310\\Scripts\\f2py.exe' -> 'C:\\Python310\\Scripts\\f2py.exe.deleteme'


[notice] A new release of pip is available: 23.3.2 -> 24.0
[notice] To update, run: python.exe -m pip install --upgrade pip


In [3]:
import numpy as np


In [11]:
random_int_array = np.random.randint(1, 50, 10)
random_int_array


array([37, 41, 44, 18, 27, 48, 28,  2,  7, 37])

In [20]:
np.mean(random_int_array)


28.9

In [15]:
random_int_array1 = np.random.randint(1, 10, size=(3, 3))
random_int_array1


array([[2, 2, 2],
       [5, 3, 6],
       [9, 2, 5]])

In [16]:
random_int_array2 = np.random.randint(1, 10, size=(3, 3))
random_int_array2


array([[8, 1, 2],
       [2, 4, 9],
       [5, 2, 1]])

In [17]:
a = np.array(random_int_array1)
b = np.array(random_int_array2)
ab = np.add(a, b)
ab

array([[10,  3,  4],
       [ 7,  7, 15],
       [14,  4,  6]])

In [21]:
np.mean(ab)


7.777777777777778

In [19]:
random_int = np.random.randint(1, 100, 10)
random_int


array([73,  4, 99, 91, 44, 67, 63, 88, 71, 10])

In [22]:
condition= random_int>50
filter=random_int[condition]
filter

array([73, 99, 91, 67, 63, 88, 71])

In [23]:
special_array = np.array([1,2,3,4,5,6,7,8,9,10])
special_array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [28]:
np.random.shuffle(special_array)
special_array

array([ 2,  1, 10,  4,  6,  5,  7,  3,  9,  8])

In [31]:
condition=special_array>6
special_array[condition]

array([10,  7,  9,  8])